

let levelOneString = "asdkjlsjkflaskdjalksdjfjkdlaskdfjskdjflkasdjfkjfkjfkdjlkasdjflkasjkjdksjfksdkfjaaasdfksdfjlkjlkjlaskdjflskdjfkasjdlfksjdkfasjkdjfkjfkdsajlkdjflskdjflaskdjfklkdkdasdfsadkjlkjkljklsjflaksjfkdjkfjkdjfkdslklsllslslslskdfjjlla";

let levelOneArray = levelOneString.split("");

export default (levelOneArray);